packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma

patchedDependencies:
  react-odontogram@0.4.1: patches/react-odontogram@0.4.1.patch
